let generateButton = document.querySelector(".container-button");
generateButton.addEventListener("click", function() {
    // Тут буде логіка генерації колоди
   let deckMain = document.querySelector(".deck-main");
    deckMain.style.display = "none";



    const buildings =  [
        "Cannon", 
        "Inferno Tower", 
        "Tesla", 
        "Bomb Tower", 
        "Goblin Hut", 
        "Mortar", 
        "X-Bow", 
        "Elixir Collector", 
        "Barbarian Hut",
        "Tombstone",
        "Goblin Cage",
    ]
    const airTroops = [
        "Baby Dragon",
        "Minions",
        "Mega Minion",
        "Minion Horde",
        "Inferno Dragon",
        "Bats",
        "Spirit Emperess",
        "Flying Machine",
        "Skeleton Dragons",
        "Electro Dragon",
        "Phoenix",
    ]
    const troopsThatGoToTower = [
        "Giant",
        "Golem",
        "Ballon",
        "Lava Hound",
        "Royal Giant",
        "Hog Rider",
        "Ram Rider",
        "Wall Breakers",
        "Miner",
        "Battle Ram",
        "Skeleton Barrel",
        "Suspusious Bush",
        "Electro Giant",
        "Elixir Golem",
        "Rune Giant",
        "Royal Hogs",
        "Graveyard",
        "Goblin Barrel",
        "Goblinstein",
        "Goblin Drill",
        ]
    const smallSpells = [
        "Zap",
        "Log",
        "Arrows",
        "Snowball",
        "Barbarian Barrel",
        "Tornado",
        "Earthquake",
        "Vines",
        "Rage",
        "Clone",
        "Royal Delivery",
        "Goblin Curse"
        ]
    const bigSpells = [
        "Fireball",
        "Poison",
        "Rocket",
        "Lightning",
        "Freeze",
        "Void",
        "Mirror",]
    const miniTnanks = [
        "Knight",
        "Valkyrie",
        "Mini P.E.K.K.A",
        "Dark Prince",
        "Prince",
        "Ice Golem",
        "Battle Healer",
        "Mighty Miner",
        "Lumberjack",
        "Fisherman",
        "Royal Ghost",
        "Rascals",
        "Bandit",
        "Furnace",
        "Skeleton King",
        "Monk",
        "Golden Knight",
        "Bowler",
        "Goblin Machine",
        "Skeleton Giant",
    ]
    const damageDealers = [
        "Musketeer",
        "Archers",
        "Dart Goblin",
        "Hunter",
        "Cannon Cart",
        "Firecracker",
        "Little Prince",
        "Witch",
        "Wizard",
        "Executioner",
        "Elite Barbarians",
        "P.E.K.K.A",
        "Boss Bandit",
        "Mega Knight",
        "Archer Queen",
    ]
    const support = [
        "Skeleton Army",
        "Goblin Gang",
        "Goblin",
        "Spear Goblins",
        "Zappies",
        "Guards",
        "Barbarians",
        "Royal Recruits",
        "Skeletons",
        "Fire Spirits",
        "Ice Spirit",
        "Heal Spirit",
        "Electro Spirit",
        "Bomber",
        "Berserker",
        "Ice Wizard",
        "Electro Wizard",
        "Magic Archer",
        "Goblin Demolisher",
        "Night Witch",
        "Mother Witch",
    ]
    console.log("Thank you for using the deck generator! Here is your deck that was generated by best deck formula:");
    const randomBuilding = buildings[Math.floor(Math.random() * buildings.length)];
    console.log("1. Building:", randomBuilding);
    const randomAirTroop = airTroops[Math.floor(Math.random() * airTroops.length)];
    console.log("2. Air troop:", randomAirTroop);
    const randomTroopThatGoesToTower = troopsThatGoToTower[Math.floor(Math.random() * troopsThatGoToTower.length)];
    console.log("3. Win conditioun:", randomTroopThatGoesToTower);
    const randomSmallSpell = smallSpells[Math.floor(Math.random() * smallSpells.length)];
    console.log("4. Small spell:", randomSmallSpell);
    const randomBigSpell = bigSpells[Math.floor(Math.random() * bigSpells.length)];
    console.log("5. Big spell:", randomBigSpell);
    const randomMiniTank = miniTnanks[Math.floor(Math.random() * miniTnanks.length)];
    console.log("6. Mini tank:", randomMiniTank);
    const randomDamageDealer = damageDealers[Math.floor(Math.random() * damageDealers.length)];
    console.log("7. Damage dealer:", randomDamageDealer);
    const randomSupport = support[Math.floor(Math.random() * support.length)];
    console.log("8. Support:", randomSupport);
});
